Theme selector setting
Railroad-Team/Railroad pull request #17
Opened 2024-05-22 21:36 UTC by YodaForce157

2024-05-22 21:44 UTC, YodaForce157 commented
About to fix major issue, give me a minute

2024-05-22 22:04 UTC, YodaForce157 commented
Fixed.

2024-05-23 12:15 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/Railroad.java
> +        getScene().getStylesheets().clear();
This is not great as a long term solution as it clears all stylesheets even if they're not necessarily themes. Instead we should consider having some kind of container holding what the current theme is and that way we can remove that specific theme from the sheets. Possibly consider a global atomic reference maybe?

2024-05-23 12:15 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/settings/ui/SettingsAppearancePane.java
> +        var themesDir = new File("themes").listFiles();
I would prefer that we avoid using java.io where possible and try to use nio. As for how you'd do that here, probably `Files.listFiles(Path)` which gives you a `Steam<Path>`.

2024-05-23 13:38 UTC, DaRealTurtyWurty requested changes

2024-05-23 13:38 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/Railroad.java
> +    public static AtomicReference<String> THEME = new AtomicReference<>("default-dark");
```suggestion
    public static final AtomicReference<String> THEME = new AtomicReference<>("default-dark");
```

2024-05-23 13:38 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/settings/ui/SettingsAppearancePane.java
> +        }
```suggestion
        List<Path> themes = new ArrayList<>();
        try(Stream<Path> files = Files.list(Path.of("themes"))) {
             files.filter(file -> file.endsWith(".css")).forEach(themes::add);
        } catch (IOException e) {
            e.printStackTrace();
        }
```

2024-05-23 13:38 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/settings/ui/SettingsAppearancePane.java
>                  String name = theme.getName().replace(".css", "");
```suggestion
                String name = theme.getFileName().toString().replace(".css", "");
```

2024-05-23 13:38 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/settings/ui/SettingsAppearancePane.java
> +        if(themeSelector.getItems().size() < themes.length + 2){
```suggestion
        if(themeSelector.getItems().size() < themes.size() + 2) {
```

2024-05-23 13:38 UTC, DaRealTurtyWurty commented on src/main/java/io/github/railroad/settings/ui/SettingsAppearancePane.java
> +            for (var theme : themes) {
```suggestion
            for (Path theme : themes) {
```

2024-05-23 14:08 UTC, DaRealTurtyWurty approved these changes

2024-05-23 14:08 UTC, merged